### ISSUE TITLE
Location and schedules of runs

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/p1-vi-runners#2]
Story: I am a VI runner that has lived and been racing with friends in Bristol area occasionally, and would like to meet more VI runners and days they run to start run with more people

**Acceptance criteria:**

- [x] Information about main locations for running
- [x] Provide information about day(s) and time(s) when the group usually goes running

**Tasks**

- [x] Create a page/section with information about the location and time to meet
