### ISSUE TITLE
Website responsiveness and accessibility

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/p1-vi-runners#3]
User story: I am a VI runner that has been running with the group and wish to be able to have clear image and information of the site and content and to easily access different contents of it.

**Acceptance criteria:**

- [x] Provide alternative means of information for VI users that might have difficulty seeing the images and content of the site
- [x] Make the site interactive and responsive

**Tasks**

- [x] Create a Navbar with high contrast for VI users and provide a description for verbal assistance.
- [x] Showcase simple and concise information in small areas of the webpage.
