### ISSUE TITLE
Socials

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/p1-vi-runners#4]
User story: I am a VI runner that would like to know more information about the group and also other sites/apps where they showcase the group

**Acceptance criteria**

- [x] Provide information about the social networks of the group
- [x] Make social information easily available on the webpage

**Tasks**

- [x] Create a section with information about the different social networks for the group
