### ISSUE TITLE
Contact and support

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/p1-vi-runners#5]
User story: I am a VI runner and would like to be able to contact the group for more information about different activities and lifts to meetings location

**Acceptance criteria:**

- [x] Provide a way for the user to contact the group
- [x] Give feedback to the user that the message was sent

**Tasks**

- [x] Create a Contact us area in the webpage
- [x] Create a message/feedback output for the user
