### ISSUE TITLE
Reviews from members

### ISSUE THREAD

**Issue by Carlos-n21** [Carlos-n21/p1-vi-runners#6]
User story: I would like to see the comments and reviews from other group members about the meetings

**Acceptance criteria:**

- [ ] Allow users to comment on the webpage about their experiences with the group
- [ ] Let members evaluate how much they enjoy the group

**Tasks:**

- [ ] Create an area for users to write their comments
- [ ] Create a section displaying different user reviews/comments
